paths: 
  jquery: 'bower/jquery/dist/jquery.min'
  backbone: 'bower/backbone/backbone-min'
  underscore: 'bower/underscore/underscore-min'
  page: 'views/page'


shim: 
  jquery: 
    exports: '$'
  
  underscore: 
    exports: '_'
  
  backbone: 
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  
  page: 
    deps: [
    ]
    exports: 'page'