paths: 
  jquery: '//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min'
  backbone: 'bower/backbone/backbone-min'
  page: 'views/page'


shim: 
  jquery: 
    exports: '$'
  
  backbone: 
    deps: ['jquery']
    exports: 'Backbone'
  
  page: 
    deps: [
      'views/gameList'
    ]
    exports: 'page'